
name: Desktop Client Nightly

on:
  schedule:
    - cron: "0 0 * * *" # run each day at 00:00 UTC
  workflow_dispatch: # allow manually triggering

jobs:
  build:
    name: Build Client
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64

      - name: Setup Ant
        uses: cedx/setup-ant@v5.1.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Setup Neutralinojs
        run: npm install -g @neutralinojs/neu

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.91.0
          default: true
          profile: default

      - name: Add Rust Support for Win32 x86_64
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install cargo-license
        run: cargo install cargo-license

      - name: Build
        run: |
          echo "steam-appid=2267890" > build.ant-private.properties
          ant nativehelper neutralinojs

      - name: Delete Previous Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete desktop-client-nightly --yes || echo "Previous nightly build release not found"
          git push origin --delete desktop-client-nightly || echo "Previous nightly build tag not found"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          name: Desktop Client Nightly
          body: Nightly builds of the Stendhal desktop client.
          tag_name: desktop-client-nightly
          prerelease: true
          files: build/stendhal-client-*.zip
